before_script:
  - apk --no-cache add python3 py3-pip

stages:
  - document
  - deploy

sphinx:
  stage: document
  script:
    - pip3 install sphinx
    - apk --no-cache add make
    - cd docs
    - make html
    - mv _build/html/ ../sphinx
  artifacts:
    paths:
      - sphinx
  tags:
    - html
  only:
    - master


pages:
  stage: deploy
  dependencies:
    - sphinx
  script:
    - mv sphinx public/
  environment:
    name: pages
    url: https://git.hq-git.soartech.com/apprentice/experta/
  artifacts:
    paths:
      - public
  tags: 
    - html
  only:
    - master

